### ISSUE TITLE
Migrate to ESLint

### ISSUE THREAD

**Issue by harunurhan** [javieraviles/node-typescript-koa-rest#52]
As you might know, `tslint` is not going to be supported any longer. (ref: https://github.com/palantir/tslint/issues/4534)

**Comment by javieraviles** [comment]
I see, didn't know so thanks for this!

Reading a bit through, there is apparently a [CLI tool](https://github.com/typescript-eslint/tslint-to-eslint-config) for migrating the config;

Will try to include this for next release :)

**Comment by javieraviles** [comment]
Just did this commit for the migration to ESLint, not sure whether you implemented this already in any projects; if so, could you have a look and give some feedback?

https://github.com/javieraviles/node-typescript-koa-rest/commit/26f3032462b2f4a7c7649e13ef9a616362862f4e

otherwise will create a PR as it is
