### ISSUE TITLE
npm run start throws an error

### ISSUE THREAD

**Issue by vycoder** [javieraviles/node-typescript-koa-rest#65]
I'm not sure what I'm doing wrong but when I running it for production:
```bash
npm run build
npm start
```

I get the following error:
```javascript
TypeORM connection error:  /home/yev/Laboratory/koa/koa-typescript/src/entity/user.ts:1
import { Entity, Column, PrimaryGeneratedColumn } from "typeorm";
       ^

SyntaxError: Unexpected token {
```

is this a typescript issue?

**Comment by javieraviles** [comment]
Hi there,

It looks like when trying to run the already built javascript, your TypeORM configuration is still pointing to the typescript entities instead of the javascript ones. Very probably, your `.env` file is still using `NODE_ENV=development` since that is the condition for TypeORM configuration to pull entities from typescript directly. Change it to any other value :)

**Comment by vycoder** [comment]
ohhh okay. I overlooked that the `entitiesPath` does indeed depend on `NODE_ENV`, now I look lazy and stupid. :)

Thanks! This project is very helpful and so are you. Thanks again!
